language: php
matrix:
  include:
  - php: 5.3
    dist: precise
env:
  - COMPOSER_REQUIRE=""
  - COMPOSER_REQUIRE="composer require masterminds/html5"
install:
  - $COMPOSER_REQUIRE
before_script: composer install
